<?php
    function printRow($x, $conn, $foreign_cascades) {
        if (!in_array($x, $foreign_cascades)) {
            echo '<tr>';
            echo '<td><a href=cascade.html?cascade='.$x.' target="_blank">BV '.$x.'</a></td>';
            echo '<td><a href=index.html?cascade='.$x.'>EB '.$x.'</a></td>';
            echo '<td>';
            $handle = fopen("../entity_score/reps/rep_".$x.".csv", "r");
            $row = 0;
            while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
                if ($row > 0) {
                    if ($row > 1) {
                        echo ', ';
                    }
                    $entity = explode(".", $data[1]);
                    echo '<a href=index.html?cascade='.$x.'&scope='.($row - 1).'>'.$entity[1].'</a>';
                }
                $row++;
            }
            echo '</td>';
            $search_query = "select count(*) from results where cascade_no=".$x;
            $result = mysql_query($search_query, $conn);
            if (!$result) {
                die('Could not run query: '.mysql_error());
            }
            echo '<td>'.mysql_result($result, 0).'</td>';
            echo '</tr>';
        }
    }
?>
<title>EasyBrowse</title>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
</head>
<body>
    <h1>EasyBrowse - the Twitter Cascade Summarisation project</h1>
    <h3>Instructions</h3>
    <ol>
        <li>Please choose a cascade that presently has the minimum number of evaluations.
        <li>Click on its <b>BaseView</b> and go through all the tweets of the conversational cascade.<br>While doing so, please note down the entities/topics that you think are important to the cascade.<br>
        <li>Click on the <b>EasyBrowse</b> view for the same cascade and click on <b>Evaluation form</b> on the left panel.
        <li>Compare the important topics of discussion generated by the system (left panel) to the topics you had noted in step 2 above.
        <li>For each topic identified by the system, you can click on the topic to see all the tweets that talk about it.<br>Amongst the highlighted tweets, select the one that you think most aptly defines what is being said about that topic in the cascade.<br>Compare it to the tweet that the system has recognised for the topic in the <b>Evaluation Form</b>.
        <li>Fill in the other details and comments on the Evaluation form and submit. :)
    </ol>
    <p><b>Note:</b> You can play around with the cascade display as per instructions mentioned at the top.</p>
    <table border="1" style="width:50%; float: left">
        <tr>
            <th>BaseView</th>
            <th>EasyBrowse</th>
            <th>Major entities</th>
            <th>Evaluation count</th>
        </tr>
        <?php
            $servername = "localhost";

            $credentials = fopen("../credentials.txt", "r");
            $user = trim(fgets($credentials));
            $password = trim(fgets($credentials));
            $database = trim(fgets($credentials));
            $conn = mysql_connect($servername, $user, $password);

            if (!$conn) {
                die("Could not connect: ".mysql_error());
            }

            mysql_select_db($database) or die("Unable to select database");

            $foreign_cascades = array(3, 8, 15, 22, 33, 42);

            for ($x = 0; $x < 12; $x++) {
                printRow($x, $conn, $foreign_cascades);
            }
        ?>

    </table>
    <table border="1" style="width:50%; float: left">
        <tr>
            <th>BaseView</th>
            <th>EasyBrowse</th>
            <th>Major entities</th>
            <th>Evaluation count</th>
        </tr>
        <?php
            for ($x = 12; $x <= 24; $x++) {
                printRow($x, $conn, $foreign_cascades);
            }
            mysql_close($conn);
        ?>
    </table>
</body>
