<?php
    function printRow($x, $conn, $foreign_cascades) {
        if (!in_array($x, $foreign_cascades)) {
            echo '<tr>';
            echo '<td><a href=cascade.html?cascade='.$x.' target="_blank">BV '.$x.'</a></td>';
            echo '<td><a href=index.html?cascade='.$x.'>EB '.$x.'</a></td>';
            echo '<td>';
            $handle = fopen("../entity_score/reps/rep_".$x.".csv", "r");
            $row = 0;
            while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
                if ($row > 0) {
                    if ($row > 1) {
                        echo ', ';
                    }
                    $entity = explode(".", $data[1]);
                    echo '<a href=index.html?cascade='.$x.'&scope='.($row - 1).'>'.$entity[1].'</a>';
                }
                $row++;
            }
            echo '</td>';
            $search_query = "select count(*) from results where cascade_no=".$x;
            $result = mysql_query($search_query, $conn);
            if (!$result) {
                die('Could not run query: '.mysql_error());
            }
            echo '<td>'.mysql_result($result, 0).'</td>';
            echo '</tr>';
        }
    }
?>
<title>EasyBrowse</title>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
</head>
<body>
    <h1>EasyBrowse - the Twitter Cascade Summarisation project</h1>
    <h3>Background</h3>
    <p>There has been an explosion of information on Social networks today and most of us have accounts on multiple social networks. Now consider this scenario:</p>
    <p>You decided you wanted to sleep early tonight and went to bed. Meanwhile, your best friend Akash posted something funny/important on Twitter. This particular tweet gained a lot of traction amongst your friends who began retweeting and replying to it. By the time you woke up in the morning, that tweet had led to a conversation (cascade) spanning 100+ tweets. Now him being your best friend, you obviously want to read through it, but reading through 100+ tweets is going to be a pain, right? What do you do in such a scenario? :(</p>
    <p>What if I gave you a crisp and short summary of all the important talking points in the cascade and also pointed you to the most important tweet for that topic?</p>
    <p>Here comes <b>EasyBrowse</b> - a system that automatically goes through cascades and does all the hard work for you, so that when you wake up in the morning, you can quickly go through the summary and be updated about all that happened while you were asleep.</p>

    <h3>The Raffle</h3>
    We are initiating a raffle where 3 users with the maximum number of evaluations will get Amazon vouchers with total prizes worth Rs. 1000<sup>*</sup>.
    <ol>
        <li>Please note that users would be uniquely identified through the name and email combination, so please use the same email id for all the evaluations that you submit.
        <li>Only one evaluation for each cascade shall be considered, so it would be better for you to evaluate the next cascade once you are done evaluating one (even if the number of evaluations of that cascade is more, refer rule 1 below).
        <li>We have built in checks in the evaluation scheme to identify fake submissions. All such non-sincere submissions shall be disregarded from the raffle.
    </ol>
    <p><sup>*</sup>: We are trying to get more funds for the prizes. Shall keep you updated here.</p>
    <b>The raffle ends on July 2, 2016</b>. So get on your evaluation glasses, keep calm and carry on! :)

    <h3>Instructions for evaluation</h3>
    <ol>
        <li>Please choose a cascade that presently has the minimum number of evaluations.
        <li>Click on its <b>BaseView</b> and go through all the tweets of the conversational cascade.<br>While doing so, please note down the entities/topics that you think are important to the cascade.<br>
        <li>Click on the <b>EasyBrowse</b> view for the same cascade and click on <b>Evaluation form</b> on the left panel.
        <li>Compare the important topics of discussion generated by the system (left panel) to the topics you had noted in step 2 above.
        <li>For each topic identified by the system, you can click on the topic to see all the tweets that talk about it.<br>Amongst the highlighted tweets, select the one that you think most aptly defines what is being said about that topic in the cascade.<br>Compare it to the tweet that the system has recognised for the topic in the <b>Evaluation Form</b>.
        <li>Fill in the other details and comments on the Evaluation form and submit. :)
    </ol>
    <p><b>Note:</b> You can play around with the cascade display as per instructions mentioned at the top.</p>
    <table border="1" style="width:50%; float: left">
        <tr>
            <th>BaseView</th>
            <th>EasyBrowse</th>
            <th>Major entities</th>
            <th>Evaluation count</th>
        </tr>
        <?php
            $servername = "localhost";

            $credentials = fopen("../credentials.txt", "r");
            $user = trim(fgets($credentials));
            $password = trim(fgets($credentials));
            $database = trim(fgets($credentials));
            $conn = mysql_connect($servername, $user, $password);

            if (!$conn) {
                die("Could not connect: ".mysql_error());
            }

            mysql_select_db($database) or die("Unable to select database");

            $foreign_cascades = array(3, 8, 15, 22, 33, 42);

            for ($x = 0; $x < 12; $x++) {
                printRow($x, $conn, $foreign_cascades);
            }
        ?>

    </table>
    <table border="1" style="width:50%; float: left">
        <tr>
            <th>BaseView</th>
            <th>EasyBrowse</th>
            <th>Major entities</th>
            <th>Evaluation count</th>
        </tr>
        <?php
            for ($x = 12; $x <= 24; $x++) {
                printRow($x, $conn, $foreign_cascades);
            }
            printRow(46, $conn, $foreign_cascades);
            mysql_close($conn);
        ?>
    </table>
</body>
